-- SQLite
CREATE TABLE IF NOT EXISTS flower (
id			INTEGER PRIMARY KEY AUTOINCREMENT,
name			VARCHAR(255) NOT NULL,
description			VARCHAR(4096) NOT NULL,
startBloom			INTEGER NOT NULL,
endBloom			INTEGER NOT NULL,
nectar			INTEGER NOT NULL,
pollen			INTEGER NOT NULL,
propolis			INTEGER NOT NULL,
melliferous			INTEGER NOT NULL
);

INSERT INTO flower (name, description, startBloom, endBloom, nectar, pollen, propolis, melliferous) VALUES
('AUBEPINE', 4, 6, 2, 3, 0, 3, 'Cet arbrisseau herisse d’epines se reconnait a la forme de ses feuilles cn « V » a la base et decouples de lobes plus ou moins profonds. Les fleurs cn bouquets, blanches et odorantes, sont portees par de petits rameaux. Liles sont surtoul visitees lorsque les autres sources de nectar sont rares Flies permetteni la production d’un miel ires prise et donnent dcs fruits ovoides, rouges, qui font la joie des oiseaux. Cette espece s’adapte a tous types de sols et supporle aussi bicn la lumiere que la mi-ombre, f lie forme l’ossature de nombreuses hales sau- vages ou d’ornement, et des lisiercs foresticrcs.')

('BOU1LLON-BLANC', 8, 9, 0, 3, 0, 2, 'Ces hautes et robustes plantes. qui peuvent atteindre 1 m, se reconnaisscnt dc loin a leuraspect elance, compact et duveteux. Elies se dressent coramc des cierges le long des voies ferrees, des friches, des talus pierreux. Les fleurs jauncs aux pctales dales en roue seserrent le Iongd’une hampe florale allongee et les feuilles ovales, assez epaisses, prennent une couleur verl-blanc a cause des poils duveteux qui les recouvrenl. C’est une source de pollen interessante cn fin d’ete, au')

('BOURDAINE', 5, 6, 2, 2, 0, 1, 'Arbrisseau atteignant 3 m, la bourdaine pos- sede des feuilles ovales altemes dont chaque ner- vure s’arque a son extremite pour se refermer sur la suivante. I.es rameaux ne sont pas epineux et ils portent dcs petites fleurs vertes qui don- neront des fruits rouges a noyau On retrouve la bourdaine aussi bien sur sols acides el humides que sur sols calcaircs et secs. Cet arbuste etait ires utilise en vannerie et pour la fabrication des balais. Le nectar contienl de la rhamnine, qui rerid le miel laxatif, maisl’effet est limile car il est le plus souvent en melange')

('BRUNELLE', 6, 9, 3, 3, 0, 1, 'Les feuilles opposees cl la tige carrce parse- mees de poils, les lleurs groupees en une inflo- rescence tertninale ovale ou presque spherique donnenl son port particulier a la brunelle Les lleurs possedenl deux levies emergeant de la base de la corolle ; la levre inferieure sert aux abeilles de piste d’atterrissage conlortablc. Cette plantc commune des bords de chcmins, des pelouses. des coupes forestieres se plait sur les sols riches plutol secs et en siluation ensoleillee. Utilisee en rocaille,')

('CALLUNE', 7, 9, 2, 1, 0, 2, 'La callune se différencie des bruyères vraies par sa fleur dont les sépales libres et membraneux sont colorés en rose, les pétales vrais formant une petite couronne rose beaucoup plus courte que le calice. Une fois fanées, les fleurs restent sur la plante et prennent une couleur grisâtre. Les feuilles, petites, sont groupées par quatre, en croix. Elle est largement répandue jusqu’à 2 500 m dans les landes ou les sous-bois clairs, sur sols acides et secs voire légèrement humides. Son nectar épais donne un miel fort, vendu à un prix élevé.')

('CENTOREE JACEE', 6, 9, 2, 1, 0, 2, 'Voilà une plante offrant aux abeilles « un panier garni » composé d’une multitude de petites fleurs tubulaires lilas regroupées en une inflorescence globuleuse, ou capitule, souvent prise pour une fleur unique. Elle est entourée à sa base d’un assemblage de minuscules bractées membraneuses brunes. Les centaurées jacées colonisent les prés, les friches et les chemins herbeux sur sols frais. D’autres centaurées, tel le bleuet, reconnaissable à la couleur bleu vif des fleurs, sont également visitées par les abeilles. Sensibles aux herbicides, certaines espèces sont en régression.')

('CERISIER', 3, 5, 2, 3, 1, 3, 'Les cerisiers fournissent un apport essentiel aux abeilles au démarrage de la ruche, permettant parfois une récolte de miel précoce. Les fleurs blanches en bouquets sont portées par de petits pédoncules attachés au rameau en un même point. Les merisiers, ou cerisiers sauvages (Prunus avium), poussent spontanément en Europe tempérée dans les taillis, les haies et les lisières, sur sols plutôt doux, argileux ou calcaires. Ils ont donné une multitude de variétés cultivées pour leur fruit. Le merisier porte à la base du limbe de chaque feuille deux glandes nectarifères rouges. Le griottier (Prunus cerasus) n’en possède pas, et ses fruits à saveur acide ne sont jamais noirs.')

('COQUELICOT', 5, 7, 0, 3, 0, 3, 'De forme ovoïde, hérissé de soies, le bouton du coquelicot se dégustait jadis en salade. Quatre pétales rouges chiffonnés et entourés de nombreuses étamines s’épanouissent ensuite. Les abeilles, aveugles au rouge, sont guidées par les fortes odeurs émises par la fleur. Compagnon indissociable du bleuet et de la marguerite, le coquelicot, originaire de l’Asie du Sud-Est, est arrivé avec les céréales cultivées. On le trouve dans les champs, les friches, le bord des chemins ensoleillés, sur sols assez riches ; il est sensible aux herbicides.')

('ERABLECHAMPETRE', 4, 5, 3, 2, 0, 3, 'Tous les érables ont une ramification, des feuilles opposées et un fruit typique où les deux graines sont entourées d’une aile membraneuse facilitant leur dispersion par le vent. L’érable champêtre est le plus mellifère. Il se reconnaît à ses feuilles à cinq lobes, à ses nervures partant toutes du même point (ce qui le différencie du platane). Les ailes du fruit sont alignées sur une seule ligne droite. Les fleurs sont en bouquets terminaux, de couleur vert-jaune. Appréciant les expositions ensoleillées ou de mi-ombre, cet arbre colonise les bois, les lisières forestières, les chênaies, les charmaies...')

('FRAMBOISIER', 5, 7, 3, 2, 0, 3, 'Cet arbrisseau, très proche des ronces, a été naturalisé dans les jardins pour l’utilisation de ses fruits. Les tiges sont faiblement épineuses et naissent à partir des souches. Les rameaux de deux ans portent des grappes de petites fleurs blanches qui donneront les fruits et mourront ensuite. Les framboisiers se rencontrent dans les clairières, les lisières, les jardins et les vergers. Ils aiment les sols frais et riches. Ils produisent un nectar important, qui donne un agréable parfum au miel.')

('GROSEILLIER', 4, 5, 1, 2, 0, 1, 'Ses feuilles possèdent de trois à cinq lobes. Des grappes de fleurs vert jaunâtre pendent à l’aisselle des feuilles ; elles donneront des baies acides, les groseilles rouges, utilisées pour les confitures ou en distillerie. Le groseillier à maquereau et le cassissier, eux aussi mellifères, s’en différencient : l’un par les épines à trois pointes ornant ses tiges, l’autre par ses grosses baies noires. Arbrisseau de moins de 2 m, le groseillier aime les terrains frais et humides et préfère la mi-ombre des bois et des forêts près des cours d’eau. Il est cultiver dans es jardins. Sa flaoraison precose en fait une source de nectar pour les abeilles.')

('HOUX', 5, 6, 2, 2, 0, 2, 'Arbrisseau d’environ 2 à 10 m, le houx est aisément reconnaissable en hiver ; ses feuilles coriaces, luisantes, piquantes et ses fruits rouges ornent les tables de fin d’année. En mai et juin, de petites fleurs unisexuées (fleurs mâles et femelles séparées) fleurissent en de nombreux petits bouquets. Son écorce était utilisée autrefois pour fabriquer de la glu et son bois reste très apprécié en ébénisterie. Il préfère la mi-ombre des sous-bois et des haies sur sols secs ou frais, mais on le trouve également dans les parcs.')

('LIERRE', 9, 10, 3, 3, 1, 3, 'Cette plante grimpante à feuilles persistantes est très fréquente dans de nombreux bois, parcs, haies. Elle présente deux types de feuilles, toutes coriaces et luisantes : d’une part, des feuilles palmées portées par les rameaux stériles poussant à terre ou sur les troncs en conditions peu lumineuses ; d’autre part, des feuilles ovales, entières, sur les rameaux fertiles dits « de lumière ». Ces derniers portent les fleurs qui sont visitées à l’automne par les abeilles. Les fleurs sont petites, verdâtres, et présentent sur le réceptacle de nombreuses glandes nectarifères qui se couvrent de gouttelettes de nectar dès que le temps devient humide.')

('LUZERNE CULTIVEE', 6, 9, 3, 1, 0, 3, 'Plante de 30 à 80 cm, aux feuilles à trois folioles allongées, elle présente une fleur caractéristique : un pétale supérieur dressé, le têtard, deux pétales inférieurs soudés et deux pétales latéraux libres, les ailes. Les fleurs violettes ou bleues sont regroupées en inflorescences allongées. Toutes les luzernes forment, après la floraison, des gousses enroulées en spirale, lisses et brunes chez cette espèce. Elle préfère les terrains argileux et se rencontre à l’état spontané dans les terrains vagues, les friches, le bord des chemins. Elle donne un excellent miel à condition de ne pas être fauchée avant la pleine floraison.')

('LUZERNE LUPULINE', 4, 10, 3, 1, 0, 2, 'C’est une plante de 10 à 30 cm à port souvent couché au sol. Ses minuscules fleurs jaunes (2 à 3 mm) sont regroupées en têtes sphériques ou un peu allongées, denses. La corolle caduque et la forme spiralée de la gousse distinguent la lupuline des trèfles dont la corolle lancée persiste sur la plante. Les feuilles possèdent trois folioles à extrémité légèrement dentée. On peut la cultiver comme plante fourragère, mais elle se rencontre surtout aux bords des chemins et des cultures. Sa floraison courte n'enlève rien à la qualité du miel récolté.')

('MAUVE', 5, 10, 2, 1, 0, 1, 'La mauve affectionne les hôtes et les roulés, lisières, remblais et terrains vagues aux sols tassés. Ses grosses fleurs naissent par deux à six, à l’aisselle des feuilles assez longuement pétiolées. Les cinq pétales présentent une petite échancrure concave à leur sommet et sont striés de lignes roses plus foncées. Les nombreuses étamines soudées en colonne par leurs filets offrent aux butineuses une gerbe compacte d’anthères jaunes. Ces fleurs se ferment à la tombée du jour ou par mauvais temps.')

('MELILOT BLANC', 7, 9, 3, 1, 0, 2, 'D’une hauteur maximale de 1 m, les mélilots se reconnaissent à leur port ramifié et à leurs tiges qui portent de longues grappes (4 à 6 cm) denses de fleurs papilionacées, blanches chez le mélilot blanc. Les feuilles sont à trois folioles allongées et dentées. Le nom « mélilot » vient du latin meli, qui signifie « miel », témoignage de l’importance mellifère historique de cette plante. Elle se rencontre sur les talus de routes, le bord des chemins, les ballasts de voies ferrées.')

('MILLEPER COMMUN', 7, 9, 0, 2, 0, 1, 'Son autre nom, "l’herbe à mille trous", évoque l'aspect des feuilles qui, à contre-jour, semblent percées de petits trous translucides. Il s'agit de glandes à essences qui confèrent au millepertuis des propriétés calmantes. Les tiges sont dressées, à feuilles opposées, et portent deux côtes. Les fleurs jaunes à cinq pétales possèdent de nombreuses étamines. Présent dans tous les lieux incultes sur sols assez secs et frais, bien que sans nectar, il est une source de pollen pour les abeilles.')

('MOUTARDE', 5, 9, 3, 2, 0, 3, 'Voilà une des plantes dont les graines sont utilisées pour fabriquer la moutarde. Sa tige de 20 à 70 cm est dressée, ses feuilles sont alternes, à lobes dentés bien découpés, et rattachées à la tige par un pétiole. Les fleurs possèdent quatre pétales jaunes et six étamines. Le fruit, ou silique, hérissé de poils blancs, ressemble à une gousse divisée en deux à l’intérieur par une cloison membraneuse. La moutarde se rencontre dans tous les lieux cultivés et dans les décombres, plutôt sur sols calcaires. Elle est très sensible aux insecticides et est traitée comme le colza.')

('NOISETIER', 1, 3, 0, 2, 0, 2, 'Le noisetier est l’un des premiers arbustes à fleurir, bien avant l’éclosion des bourgeons. Il porte sur le même pied des fleurs mâles en chatons pendants et des fleurs femelles dont seuls émergent les stigmates rouge vif. Les feuilles, alternes, dentées, ont une forme un peu en cœur et une consistance finement veloutée. On le rencontre dans toute la France. Sa floraison très précoce en fait une importante source de pollen dès janvier, et il est à l’origine du mielat après émergence des feuilles.')

('ORIGAN ', 7, 9, 2, 1, 0, 2, 'Les fleurs d'origan, petites, s’épanouissent en nombreux bouquets portés chacun par un pédoncule. Chaque fleur a deux lèvres et des étamines et stigmates saillants qui favorisent la pollinisation de la plante par d’autres insectes que les abeilles : en effet, seul le nectar semble être utilisé par celles-ci. Les feuilles, ovales et opposées, dégagent une odeur caractéristique à la froissure, due aux huiles essentielles synthétisées par la plante. Assez commun, l’origan affectionne les talus et les coteaux secs sur sols calcaires. On l’utilise en condiment dans les pays méditerranéens.')

('PEPLIER TREMBLE', 3, 4, 0, 2, 1, 3, 'Le peuplier tremble est largement panaché pour l’utilisation de son bois (pâte à papier, allumettes, poteaux). Ses feuilles sont presque rondes, régulièrement ondulées sur les bords. Le pétiole perpendiculaire au limbe permet un mouvement de la feuille au moindre souffle d’air, d’où son nom de « tremble ». L’aspect collant des bourgeons est dû à la sécrétion d’une résine, récoltée par les abeilles, qui la transforment en propolis. Les chatons de fleurs mâles apparaissent avant les feuilles et donnent à l’arbre des reflets gris et soyeux. Cet arbre affectionne les milieux humides : berges de ruisseaux, champs inondables, graviers des rivières.')

('PISSENLIT', 5, 6, 3, 3, 0, 3, 'Des fleurs jaunes en languettes, portées par une tige creuse produisant un lait blanc à la cassure, des feuilles longues en rosette à la base, plus ou moins profondément divisées en lobes triangulaires caractérisent le pissenlit. Ses fruits sont surmontés d’un petit « parachute » facilitant leur dispersion par le vent. Les pissenlits sont très visibles dans les milieux ouverts sur sols riches, neutres ou légèrement acides : jardins, bois clairs, décombres, talus... Au printemps, sur les prairies de montagne, ils permettent la production d’un miel original.')

('POIRIER', 3, 5, 2, 1, 0, 2, 'C’est un arbre ou un arbuste à écorce lisse et verdâtre dans le jeune âge, qui vire ensuite au brun et se fissure en écailles. Les rameaux, dont les plus jeunes peuvent se terminer par une épine, portent des feuilles alternes ovales, longuement pétiolées, luisantes et plus foncées sur le dessus. Les fleurs sont groupées en bouquets de dix à douze. Leurs nombreuses étamines pourpres les distinguent des fleurs de pommier. Le poirier a une large amplitude écologique mais...')

('POMMER', 3, 5, 3, 1, 0, 3, 'L’écorce écailleuse du pommier est brun-rouge et ses rameaux peuvent porter quelques épines. Les feuilles alternes sont plus longues que le pétiole. Les fleurs blanches, parfois rosées, aux étamines jaunes se regroupent par quatre ou huit en petits bouquets. Cet arbre est très tolérant mais préfère la lumière ou la mi-ombre. Sa floraison plus longue, la densité des plantations et son nectar plus abondant le rendent plus intéressant que le poirier pour les abeilles. Même les colzas voisins d’un verger sont délaissés au profit des pommiers en fleurs.')

('PRUNELLIER', 3, 4, 2, 2, 0, 3, 'Arbrisseau très épineux à écorce gris-noir, le prunellier drageonne intensément et forme des peuplements denses et impénétrables dans les lisières forestières, les haies, les pelouses sèches, les friches. Ses feuilles alternes sont ovales, finement dentées, de forme allongée à elliptique. Avant les feuilles s’épanouissent de petites fleurs (environ 1 cm de diamètre) solitaires ou groupées par deux le long des rameaux. Il tolère une grande variété de conditions mais affectionne les sols riches et calcaires.')

('ROBINIER', 5, 6, 3, 3, 0, 3, 'Le robinier est l’un des rares arbres de la famille des Fabacées sous nos climats. Dès sa cinquième année, il offre des grappes de fleurs blanches odorantes en quantité. Ses feuilles possèdent jusqu’à dix paires de folioles et deux fortes épines marquent la base du pétiole. Il tolère aussi bien les sols riches que pauvres, sur tout type de substrat. Très résistant à la pollution, il est souvent planté en ville. Le robinier est à l'origine d’un miel réputé, très doux, bien connu sous le nom de « miel d'acacia ».')

('RONCE', 6, 8, 2, 2, 0, 3, 'Les tiges de ronces, armées de cruels aiguillons, ont un port dressé la première année puis s’enracinent la deuxième année par marcottage. Les feuilles sont composées de trois folioles grossièrement dentées. Des grappes de fleurs à cinq pétales blancs ou roses ornent le sommet des rameaux et donneront les mûres. En France, on trouve une soixantaine d’espèces de ronces, très difficilement identifiables. Elles poussent en lisière des bois, dans les haies, les friches et sont très visitées par les abeilles.')

('SAINFOIN', 5, 8, 2, 0, 0, 2, 'Autrefois largement cultivé comme fourrage et à l’origine d’un miel réputé, le sainfoin s’est raréfié, sauf en montagne, où il pousse spontanément (Onobrychis vicifolia). Les fleurs d’Onobrychis vicifolia sont d’un rose soutenu, souvent striées de rouge, insérées en grappes terminales allongées qui dépassent les feuilles. L’étendard, les deux ailes et les deux pétales inférieurs sont caractéristiques des Fabacées. Le sainfoin aime les terrains plutôt secs et calcaires, les coteaux ensoleillés. Le sainfoin d’Espagne, typiquement méditerranéen, est également mellifère.')

('SALKAIR', 6, 9, 3, 2, 0, 2, 'Plante affectionnant les milieux humides, les bords de ruisseaux, la salicaire se distingue par ses fleurs à six pétales rose vif insérées en petits groupes compacts, ou glomérules, à la base des feuilles, et sa tige à quatre angles. Les feuilles sont lancéolées, souvent en cœur à leur base, les inférieures opposées par deux ou trois puis devenant alternes vers le bas de la tige.')

('SCABILEUSE', 7, 10, 3, 1, 0, 3, 'La scabieuse est une plante vivace portant des capitules terminaux de fleurs lilas violacé. Chaque fleur est formée d'une corolle à pétales soudés et inégaux d'où émergent quatre étamines. Les feuilles sont duveteuses et découpées en lobes assez étroits. Les scabieuses peuvent être confondues avec les knauties, dont elles se différencient par la présence de petites paillettes membraneuses sur le réceptacle des fleurs. La scabieuse se rencontre aussi bien sur terrains secs et calcaires que sur terrains acides à sols plus profonds.')

('TIEULLS', 6, 7, 3, 2, 0, 3, 'Arbres à grande longévité (jusqu’à 1 000 ans pour le Tilia platyphyllos), les tilleuls possèdent des feuilles alternes, presque rondes, en cœur à la base et terminées par une pointe légèrement asymétrique. Les fleurs sont petites, blanches, régulières, à cinq pétales et à nombreuses étamines. Elles donnent des fruits secs qui restent attachés à la bractée qui les portait. Les tilleuls aiment la mi-ombre. La sécrétion de nectar peut être très importante par temps peu humide et assez chaud. Les nectars de Tilia oliveri, Tilia euchlora, Tilia tomentosa et Tilia dasystyla sont considérés comme toxiques pour les abeilles.')

('TREFLE BLANC', 5, 7, 3, 2, 0, 3, 'Cette plante se caractérise par sa tige couchée émettant régulièrement des racines, ses fleurs blanchâtres en têtes globuleuses (30 à 250 fleurs par tête) terminant le pédoncule floral. Les fleurs fanées restent sur la plante et prennent un port retombant après la pollinisation. Les feuilles sont à trois folioles. Le trèfle blanc forme d’abondants peuplements, très visités par les abeilles dans les prairies naturelles, les gazons, le bord des chemins et des cultures, et aussi en montagne. Il est une des plantes les plus mellifères, surtout dans la moitié nord de la France.')

('TREFLE INCARNAT', 5, 7, 3, 1, 0, 3, 'Trèfle d’assez grande taille (jusqu’à 50 cm), peu ramifié et velu, il se distingue par ses inflorescences cylindriques et allongées, aux fleurs d’un beau rouge carmin. On le rencontre dans les prés, les décombres et il est cultivé comme plante fourragère. La floraison peut se prolonger deux semaines si la plante n’a pas été fécondée. Les abeilles se nourrissent de nectar le matin et butinent le pollen l’après-midi.')

('TROENE', 5, 6, 2, 1, 0, 2, 'Arbrisseau ne dépassant pas 3 m, le troène se reconnaît à son écorce beige, ses feuilles opposées, luisantes et allongées, qui se rattachent au rameau par un court pétiole. Les fleurs blanches, odorantes, sont regroupées en grappes terminales ; leurs quatre pétales sont soudés à la base puis divisés en quatre lobes égaux. Les baies noires, de la taille d’une groseille, persistent une partie de l’hiver. Le troène préfère les sols riches, calcaires et un peu secs, mais tolère l’humidité. Il est fréquent dans les bois tempérés, les haies, les friches.')

('RUSSILAGE', 2, 4, 0, 1, 0, 2, 'Une des rares plantes dont les fleurs apparaissent avant les feuilles dès le mois de février en plaine. Des capitules solitaires de fleurs jaunes (en tube et avec des ligules) sont portés par des tiges assez épaisses. Les feuilles sont de grande taille, ovales et en cœur à la base. Affectionnant les terrains vagues, les remblais et les sols nus, le tussilage constitue un apport intéressant au démarrage de la ruche.')

('VERGE D'OR', 7, 10, 2, 2, 0, 2, 'Plante haute de 20 à 120 cm, la verge d’or possède des feuilles alternes, ovales plus ou moins allongées (lancéolées), réparties le long de la tige. Des rameaux dressés portent les inflorescences, semblables à celles des marguerites, mais dont les fleurs centrales en tubes et les fleurs externes en languettes sont toutes jaunes. On trouve la verge d’or au sein des forêts claires, des coupes, des décombres et des remblais. Cette plante est utilisée dans la ruche comme provision d’hiver ; le miel pur, de couleur verte, possède un fort goût.')

('VIPERINE', 5, 7, 3, 4, 0, 1, 'La vipérine est hérissée de poils raides, presque piquants. Ses fleurs passent souvent du rose au bleu, et leurs lobes inégaux évoquent des mâchoires de vipère, d’où son nom. Elles sont regroupées en une inflorescence s’enroulant en crosse à l’aisselle des feuilles supérieures. Les feuilles inférieures sont munies d’un pétiole, contrairement aux supérieures. La vipérine aime les sols légers, acides ou basiques, dans des milieux secs et chauds : décombres, gravières, bords de chemins… Elle peut être une ressource non négligeable, mais elle est très sensible aux désherbants sélectifs.')

('BRUYER INCARNATE', 3, 7, 2, 2, 0, 3, 'Bruyère typiquement alpine, Phyllodoce caerulea (anciennement Phyllodoce nivalis ou Picea minima), se rencontre dans les bois de conifères, les rocailles et les landes, sur tous types de sols, jusqu’à 3 000 m d’altitude. Ses feuilles sont verticillées par quatre, en aiguilles très étroites ne dépassant pas 1 cm de long. Les fleurs, en forme de grelots roses, sont disposées d’un seul côté du rameau. Elles possèdent un anneau nectarifère à la base de l’ovaire, comme toutes les bruyères. Sa floraison très précoce et sa bonne capacité nectarifère en font une plante intéressante pour les abeilles au début de la saison, lors du redémarrage des colonies.')

('CHATAIGNIER', 6, 7, 2, 2, 0, 2, 'L'arbre élancé possède, dans sa jeunesse, une écorce grise et lisse, qui brunit et se crevasse longitudinalement par la suite. Ses feuilles alternes, longues de 10 à 25 cm, ont des dents espacées et des nervures latérales saillantes. Les fleurs mâles sont regroupées en longs chatons odorants, tandis que les fleurs femelles donnent des châtaignes enfermées dans une bogue épineuse. Cet arbre est spontané en Corse, dans les Pyrénées-Orientales et en quelques points des Cévennes. Il a été introduit partout ailleurs. Il se rencontre surtout sur sols acides, jusqu’à 1 000 m d’altitude.')

('EPILOBE EN EPIS', 6, 9, 3, 2, 0, 3, 'Les feuilles de cette grande plante vivace sont allongées et étroites. Ses fleurs rose-pourpre, de bonne taille (jusqu'à 3 cm de diamètre) et à quatre pétales, sont disposées en longues grappes fournies. Elles donneront des fruits allongés, s’ouvrant par quatre valves et libérant des graines surmontées de soies, qui confèrent au fruit, tout juste ouvert, un aspect plumeux. L’épilobe, aussi appelé laurier de Saint-Antoine, aime les sols frais, riches et la lumière. Souvent présent en vastes populations, il colonise le bas des prairies, les bois clairs, les coupes et les lisières. Il se rencontre également en plaine.')

('EPILOBE HERISSE ', 6, 9, 2, 2, 0, 2, 'Si son aspect général évoque celui du laurier de Saint-Antoine, son cousin proche, l’épilobe hérissé, s’en distingue par son écologie, beaucoup plus liée aux milieux humides, aux sols inondables ou marécageux. Il se rencontre un peu partout en France, jusqu’à 1 500 m d’altitude. Sa tige est velue, avec des feuilles opposées ; elle porte, à l’aisselle des feuilles, quelques grappes de fleurs dont les pétales sont échancrés à leur sommet.')

('GERMANDREE DES MONTAGNES', 5, 8, 2, 1, 0, 2, 'C’est une des rares plantes de cette famille dont la fleur ne possède pas de lèvre supérieure, les étamines saillant directement à l’extérieur, au-dessus de la lèvre inférieure. Plante ligneuse à la base, rampante, elle porte des amas terminaux de fleurs jaune ou jaunâtres. Ses feuilles coriaces, à bords enroulés et à duvet sur la face inférieure, sont adaptées aux conditions rudes, sèches et ensoleillées des rochers ou pelouses calcaires pionnières qu’elle affectionne.')

('HELLEBORE', 1, 4, 2, 2, 0, 1, 'C’est une des premières plantes herbacées à fleurir, d’où son autre nom de « rose de Noël ». Elle possède des fleurs solitaires, blanches à roses, en forme de coupe, qui offrent aux abeilles des glandes nectarifères à la base des étamines. Ses feuilles découpées en folioles allongées partent toutes de la base de la plante. Elle préfère les sols calcaires assez secs à frais et se rencontre dans les bois, les broussailles et les rocailles jusqu’à 1 900 m. Bien qu’assez rare, elle peut être intéressante en raison de sa floraison précoce.')

('MELEZE', 6, 9, 0, 0, 0, 1, 'Seul conifère européen à épines caduques, il peut atteindre 30 m de haut et possède un tronc bien droit. Ses aiguilles, d’un vert clair, regroupées en touffes de trente à quarante sur de petites protubérances, sont douces au toucher. Les cônes sont courts et globuleux. C’est une essence de lumière qui aime les atmosphères sèches et liées et ne craint pas le froid : on le trouve à l’état spontané dans les régions du sud des Alpes, et en plaine où il est planté. Parce qu’il cristallise dès qu’il est stocké dans la ruche, les abeilles ne peuvent consommer le miellat de mélèze, et les apiculteurs détruisent les cadres qui en sont remplis.')

('PERCE-NEIGE', 1, 3, 1, 1, 0, 1, 'C’est l’une des premières plantes vivaces à bulbe à fleurir. Si sa quantité de nectar est faible, elle permet aux abeilles d’avoir une activité dès les premiers rayons de soleil. L’iris se reconnaît à ses deux feuilles linéaires vert bleuté, lisses et un peu charnues. Les fleurs solitaires émergent d’une bractée membraneuse et pendent comme de petits lampions. Pétales et sépales sont de couleur blanche, les trois pièces internes étant marquées d’une tache verte à leur sommet. Le perce-neige se rencontre jusqu’à 1 800 m dans les bois, les prairies, les vergers sur sols profonds.')

('REDODINDERON ', 6, 7, 3, 0, 0, 2, 'Les rhododendrons marquent le paysage de leurs buissons épais, bas (pas plus de 1 m), qui illuminent en début de saison la lande alpine d’une généreuse floraison rose-pourpre. Ils succèdent en altitude aux derniers conifères, lorsque les conditions deviennent trop rudes. On reconnaît le rhododendron ferrugineux à ses feuilles, dont la face inférieure est de couleur rouille, et à sa nette préférence pour les sols siliceux. En revanche, les feuilles du rhododendron hirsute sont vertes sur les deux faces (malgré la présence de glandes rouille) et il ne se rencontre que sur sol calcaire.')

('SAPIN', 5, 5, 0, 1, 0, 2, 'Aie dense dans les forêts entre 800 et 1900 m, le sapin se reconnaît à ses branches étalées, à ses cônes dressés (à la différence de ceux de l’épicéa), ainsi qu’à son écorce grise. Ses aiguilles solitaires sont attachées sur le rameau par un petit disque. Elles portent deux lignes blanches sur la face inférieure. Le sapin exige en permanence une atmosphère humide et est souvent lié au hêtre, sur les pentes exposées au nord. Le miellat donne un miel recherché par certains, mais sa production est irrégulière, car la présence de pucerons en nombre important est sujette à une conjonction de facteurs climatiques.')

('SERFOLET', 6, 9, 2, 0, 0, 2, 'On peut le confondre facilement avec le thym vulgaire, mais ce dernier est plutôt méditerranéen alors que le serpolet se trouve naturellement dans toute la France, notamment en montagne jusqu’à 3 000 m. Il s’en différencie par ses feuilles ovales, non enroulées sur les bords et à base ciliée. Le serpolet, bien que vivace, est moins ligneux que le thym et présente plutôt des tiges rampantes sur lesquelles s’insèrent directement les racines. Il affectionne les lieux herbeux et rocailleux, les broussailles.')

('SORBIER DES OISELEURS', 5, 6, 2, 1, 0, 2, 'C’est un arbuste qui offre une floraison généreuse en bouquets terminaux de fleurs blanches et odorantes. Ses feuilles alternes et composées possèdent de neuf à quinze paires de folioles ovales, allongées en série, luisantes sur leur face supérieure. Il se reconnait aisément lors de la fructification, se couvrant en abondance de superbes baies rouge corail qui font le délice des grives (elles sont toxiques pour l’homme). Ce sorbier se rencontre naturellement dans les landes de montagne, jusqu’à 2 400 m, mais il a été largement planté dans les parcs et jardins.')

('ABICOTIER', 2, 4, 1, 3, 0, 2, 'L'abricotier, originaire du Caucase, est un arbuste sans épines pouvant atteindre 4 m de hauteur et dont les fleurs apparaissent avant les feuilles. Ses fleurs sont blanches, parfois teintées de rose, à nombreuses étamines et elles sont insérées pratiquement sans pédoncule sur un rameau de l'année précédente, solitaires ou par petits groupes. Les feuilles, arrondies à ovales, doublées dentées sont en cœur à la base et portent des glandes nectarifères sur le pétiole. L'abricotier préfère les sols peu compacts ou profonds et pauvres en calcaire.')

('AMANDIER', 2, 4, 3, 2, 0, 3, 'Les fleurs de l’amandier s’épanouissent à la sortie de l’hiver, avant les feuilles. L’amandier est défendu par des épines formant certains rameaux, dont le port entremêlé accentue le côté impénétrable. Les feuilles sont typiquement lancéolées, à court pétiole portant des glandes. L’espèce domestique est cultivée pour sa graine, l’amande douce, tandis que l’amande sauvage amère contient de l’acide prussique toxique. Cet arbuste aime les loess légers et sablonneux. Sa floraison précoce le rend surtout utile pour le démarrage du couvain.')

('ARBOUSIER', 10, 1, 2, 0, 0, 2, 'Arbuste typique du maquis, où il peut atteindre 1 à 2 m de haut, l’arbousier se reconnaît à ses feuilles alternes persistantes, de forme ovale, coriaces et luisantes. Il est planté comme arbre ornemental dans le nord de la France. Les fleurs forment des clochettes verdâtres portées par un pédoncule assez court; elles donneront de grosses baies orangées, devenant rouge vif à maturité et hérissées de petites vermines soyeuses. On les utilise pour la faire de la confiture ou du cau-de-vin. Quant au nectar d’arbousier, lorsqu’il est en trop grande quantité, il donne une véritable amertume au miel.')

('ASPHODELE', 4, 6, 1, 0, 0, 1, 'Grande et robuste plante des maquis et garrigue, parfois en larges populations. L’asphodèle se reconnaît à sa longue hampe florale qui porte des fleurs régulières à six pétales blancs traversés d’une ligne centrale orangée. Ses feuilles sont triangulaires, élancées et légèrement charnues. Peu souvent mentionnée dans les ouvrages apicoles, l’asphodèle représente une source de nectar non négligeable pour les abeilles.')

('BRUYER BLANCHE', 3, 5, 1, 2, 0, 2, 'Aussi dénommée bruyère arborescente, elle marque de sa silhouette aux longues grappes ramifiées de fleurs blanches les maquis de la plaine et des collines méditerranéennes. D’assez grande taille pour une bruyère — jusqu’à 3 m — elle possède des feuilles ressemblant à des aiguilles très courtes (3 à 4 mm) et fines, insérées par trois ou quatre sur les rameaux. Les fleurs sont odorantes et se reconnaissent bien à leur port pendant et au stigmate dépassant largement les clochettes élargies au sommet. On la trouve sur sols siliceux, aussi bien dans les fourrés que sur les talus, au bord des eaux.')

('BUIS', 4, 5, 2, 1, 0, 1, 'Arbuste aux feuilles persistantes, opposées, luisantes et coriaces, le buis est très largement répandu en région méditerranéenne. Il remonte pourtant jusqu’en Bourgogne et dans le Jura, où on peut trouver des populations importantes dans des zones relativement éboulées. Ailleurs, il sera disséminé, souvent issu de cultures ornementales, notamment des parcs et jardins, où il est très utilisé. Les fleurs verdâtres sont regroupées à l’aisselle des feuilles. S’il aime la chaleur, il s’accommode de sols secs à frais, tant qu’ils ne sont pas trop profonds.')

('CHARDON A EGUILLES ', 5, 6, 1, 1, 0, 2, 'Connu la plupart des chardons, cette plante possède des feuilles alternes à pointes très épineuses. La tige porte une aile épineuse qui disparaît progressivement de la base vers le sommet. Les fleurs pourpres sont réunies en tubes et sont regroupées en une tête solitaire semi-sphérique ; elles donneront des fruits surmontés d’un petit parachute. Le chardon méditerranéen se rencontre dans les friches, sur les coteaux et champs où il côtoie d’autres espèces de chardons et de discos, avec lesquels il peut se confondre facilement (seuls les fruits les distinguent).')

('CHENE MEDITERANEENS', 3, 5, 0, 0, 0, 2, 'Ces trois chênes possèdent des feuilles persistantes, qui restent vertes toute l'année. Elles sont unilatérales, à face supérieure plus ou moins luisante. Celles du chêne vert (Quercus ilex) sont les plus polymorphes, et de toutes tailles, avec ou sans dents. Le chêne kermès (Quercus coccifera) possède les plus petites, aux dents légèrement piquantes. Le chêne liège (Quercus suber) est connu par son écorce, prélevée sur l’arbre tous les dix à quinze ans. Le gland du chêne kermès, dont la tourelle comporte des épines, le distingue des deux autres espèces. Comme les autres chênes, ces arbres abritent des pucerons à l'origine du miellat du chêne.')

('CISTE BLANC', 4, 6, 0, 2, 0, 1, 'Les cistes ont en commun des tiges ligneuses, des feuilles opposées, des fleurs à cinq pétales d’aspect froissé et de nombreuses étamines. Ils se différencient par la couleur des fleurs, l’aspect des feuilles et leur préférence écologique. Le nom du ciste blanc (à fleurs roses !) vient de l’aspect de ses feuilles, duveteuses et de couleur vert-blanc. Il se rencontre dans les garrigues et les bois clairs. La couleur orange tirée du pollen se reconnaît sur les pelotes des abeilles.')

('GISTES', 4, 6, 0, 2, 0, 1, 'Ces deux iris ont des fleurs blanches, mais le ciste de Montpellier (Cistus monspeliensis) possède souvent des taches jaunes à la base des pétales, guides visuels pour les abeilles. Ses feuilles sont collantes. Comme le ciste blanc, il affectionne les garrigues et coteaux secs calcaires. Le ciste à feuilles de sauge (Cistus salvifolius) ne possède pas de feuilles collantes et s’installe sur terrains siliceux (maquis bas, rochers). Ces deux arbrisseaux ont des feuilles opposées et des fleurs à cinq pétales (mâles et à nombreuses étamines).')

('CLEMENTINIER', 3, 5, 3, 2, 0, 1, 'Comme tous les agrumes, le clémentinier possède des feuilles et des fleurs très odorantes grâce aux glandes à essences logées dans ses tissus. Cet arbrisseau de 4 à 6 m de haut a des feuilles persistantes, un peu coriaces et luisantes. Ses fleurs blanches formeront les clémentines, variété de mandarine sans pépins. Il est apparu au début du siècle, mais son origine reste incertaine (issu d’un croisement dirigé ou importé d’Asie). Il aime les terrains ensoleillés, non calcaires, et n’aime pas les températures basses : sa culture est importante en Corse et on ne le trouve pas hors de la zone méditerranéenne.')

('DORYCNILIM', 4, 5, 2, 1, 0, 2, 'Cet arbrisseau très rameux, à petites feuilles courtes (moins de 1 cm), est également appelé badasse. 1 folioles et stipules, semblables, donnent l’impression de cinq feuilles digitées. Les fleurs d’un blanc bleuté sont groupées en têtes globuleuses au sommet d’un long pédicelle. De type « papilionacé », elles présentent un étendard, deux ailes sur les côtés et une carène tachée de noir. La badasse se rencontre de préférence sur sol calcaire dans les lieux arides du Midi : coteaux, garrigue, haies. C’est un arbuste activement visité par les abeilles.')

('EUCALIPTUS', varie, varie, 3, 1, 0, 2, 'Cet arbre élevé se reconnait à son odeur typique. Son écorce lisse se xfolie en lambeaux. Ses feuilles coriaces et glancées persistent toute l’année. Les fleurs forment des bouquets d'où émergent de nombreuses étamines. Original de l’Australie, il a été planté dès la seconde moitié du XIXe siècle, afin de drainer les marécages des zones méditerranéennes, et il est maintenant naturalisé. On peut le rencontrer sur le littoral atlantique. Chaque espèce a des propriétés mellifères différentes.')

('FERULE', 7, 8, 3, 1, 0, 2, 'Cette grande ombellifère qui peut dépasser 5 m se reconnait aisément à ses ombelles de petites fleurs jaune-vert vif et sa tige épaisse, sineuse et creuse. Les feuilles sont découpées en fines lanières et leur base forme une gaine proéminente autour de la tige. Dans l’Antiquité, la férule permettait de transporter le feu grâce à sa tige se consumant très lentement et à sa moelle, qui faisait office d’allumeur. Elle préfère les garrigues, les bords des routes et les talus sur calcaire.')

('HELIANTHEME', 3, 4, 0, 1, 0, 2, 'Proches des cistes, les hélianthèmes se distinguent par leur taille (50 cm tout au plus), par leur tige herbacée ou tout juste ligneuse à la base et enfin par leurs fleurs, jamais roses. Les feuilles sont petites, males à élancées. Les fleurs sont froissées et prennent une allure penchée après la floraison. Chez pratiquement toutes les espèces, les sépales du calice sont inégaux : trois grands et deux petits. L’hélianthème des Apennins possède des fleurs blanches, alors qu’elles sont jaunes chez les autres espèces. Les hélianthèmes préfèrent les sols calcaires.')

('HYSOPE', 7, 9, 2, 2, 0, 1, 'Cette magnifique plante vivace présente un aspect compact où les fleurs à deux lèvres sont mêlées aux feuilles lancéolées ou linéaires. La lèvre supérieure des fleurs présente une courbure concave, dressée vers l’arrière, et la couleur bleu-violet ou violacée des pétales est remarquable. L’hysope affectionne les terrains arides et rocailleux jusqu’à 2 000 m. C’est une ressource occasionnelle pour les abeilles car les populations sont dispersées.')

('LAURIER', 2, 6, 1, 1, 0, 2, 'Arbrisseau à feuilles persistantes, males à lancéolées, coriaces et opposées, le laurier-tin se rencontre dans les bois denses, les fourrés et les garrigues, mais est également utilisé comme plante d’ornement dans les parcs et jardins. Les fleurs blanches à pétales sondés sont groupées en une sorte d’ombelles assez plates (ou corymbes) qui donnent leur aspect typique aux plantes de ce genre, les viornes. Elles fourniront des baies globuleuses noires et toxiques')

('LAVANDE MARITIME', 3, 6, 3, 1, 0, 3, 'La lavande maritime, ou lavande stoechade, plante vivace au parfum si caractéristique, est un petit arbrisseau dense à la base, d’où vont émerger des tiges bien fermes. Les fleurs se regroupent en épis de forme carrée surmontés de bractées violettes qui attirent visuellement les abeilles. Les feuilles, opposées, sont linéaires, étroites, à marges enroulées vers la face inférieure et elles sont recouvertes de poils gris conférant une couleur bleu-vert à la plante. Cette lavande ne se développe naturellement que sur silice.')

('LAVANDE ', 6, 9, 3, 1, 0, 3, 'La lavande à feuilles étroites (Lavandula angustifolia) se distingue de la lavande marocaine par ses inflorescences en épis plus ou moins lâches. Les feuilles sont étroites, opposées à bords enroulés. Elle préfère les sols calcaires, chauds, rocailleux, mais s’accommode de sols un peu acides. Le lavandin (L. angustifolia × latifolia) est une hybridation entre la lavande à feuilles étroites et la lavande à feuilles larges ; cultivé pour ses propriétés aromatiques et ses huiles essentielles, il possède la production de nectar la plus intéressante qualitativement et quantitativement, tout au moins dans les régions chaudes.')

('NERPRUN ALATERNE', 2, 4, 0, 2, 0, 2, 'Cet arbuste à écorce grise et à feuillage persistant est peu exigeant et se rencontre autant sur silice que sur calcaire. Ses feuilles alternes, coriaces et luisantes sont munies de dents espacées et effilées qui peuvent les faire confondre avec celles du houx. Les fleurs mâles et femelles sont séparées et s’insèrent en petits groupes à l’aisselle des feuilles. Les fleurs femelles donnent de petites baies rouge foncé devenant noires à maturité.')

('PECHER ', 3, 4, 0, 2, 0, 2, 'Le pêcher se distingue des autres fruitiers de la même famille (abricotier, prunier, cerisier ...) par ses feuilles allongées, finement dentées et à court pétiole dépourvu de glandes nectarifères. Elles sont pliées plus ou moins fortement le long de la nervure principale. Les fleurs sont roses, parfois lavées de blanc. Le pêcher craindrait l’humidité, préfère les sols légèrement calcaires et bien drainés. De nombreuses variétés sont cultivées en région méditerranéenne, donnant un miel très fin bien qu’en très faible quantité : le nectar est souvent totalement utilisé par le couvain.')

('ROMARIN', 11, 4, 3, 1, 0, 2, 'Il pousse dans les garrigues et maquis proches de la mer et c’est aussi présent, dans le sud de la France, jusqu’à 700-800 m. Arbrisseau très ramifié, il parfume son milieu d’une odeur aromatique très reconnaissable. Ses fleurs bleu del, parfois blanches ou roses, peuvent apparaître plusieurs fois dans l’année. Seule la lèvre inférieure de la fleur est bien développée, la supérieure se divisant en deux pétales étroits. Les feuilles étroites, linéaires et persistantes, à marges enroulées vers la face inférieure sont recouvertes d’un feutrage blanchâtre.')

('SARRIETTES', 6, 9, 0, 2, 0, 2, 'La sarriette des montagnes (Satureja montana) est un petit arbrisseau aromatique à fleurs blanches ou roses rassemblées en petits groupes à l'aisselle des feuilles. Elle colonise les coteaux arides et pierreux méditerranéens mais elle remonte jusque dans les Cévennes et les Hautes-Alpes. Ses feuilles opposées sont lancéolées, légèrement plus larges au-dessus de leur milieu. La sarriette des jardins (Satureja hortensis) s'en différencie notamment par ses fleurs un peu plus petites (4 à 7 mm). Tout aussi aromatique, c’est une plante annuelle, non ligneuse, très cultivée.')

('THYM', 4, 9, 3, 0, 0, 2, 'Petit arbrisseau aromatique, ligneux, le thym se reconnaît à ses petites feuilles mâles à linéaires, duveteuses sur la face inférieure. De ses fleurs roses ou blanches à deux lèvres émergent les étamines. Le thym est largement cultivé dans les jardins ou sur de plus grandes surfaces pour ses propriétés aromatiques. Dans la nature, il apprécie les terrains calcaires caillouteux et secs. Il existe une dizaine d’espèces de thym en France comme le serpolet, un peu moins nectarifère, ou le thym citron —, qui ne possèdent pas toutes les mêmes exigences écologiques.')

('CAROTTE', 5, 7, 1, 2, 0, 1, 'Elle porte des ombelles de petites fleurs blanches ou roses sur lesquelles semble avoir été déposée une fleur centrale pourpre-noir. Les bractées (lanières découpées sous l’ombelle) se fléchissent vers la tige et les feuilles molles sont très découpées. Cette plante bisannuelle forme une racine comestible à la fin de la première année, avant de développer les fleurs la deuxième année. On la rencontre à l'état sauvage dans les friches, les prés et les chemins, ou en culture porte-graine. Le miel de carotte n’est pas toujours de très bonne qualité.')

('COLZA', 4, 5, 2, 2, 0, 3, 'Le colza est une plante herbacée, très voisine du navet, à hautes tiges robustes, pouvant dépasser 1 m, de teinte vert bleuté et d’aspect un peu cireux. Sa floraison jaune vif embaume l’air d’une odeur forte. Ses fleurs possèdent quatre pétales, six étamines et quatre glandes nectarifères à la base des étamines. Ses feuilles ont des lobes plus ou moins découpés. Le colza est abondamment cultivé dans toute la France, sauf en régions montagneuse et méditerranéenne, mais les traitements insecticides auxquels il est soumis ne sont pas sans poser de problèmes aux abeilles.')

('MAÏS ', 6, 8, 0, 2, 0, 1, 'Originaire des hauts plateaux mexicains, le maïs est l'une des céréales les plus cultivées à travers le monde. De haute taille (jusqu'à 3 m), sa tige très robuste est garnie de larges feuilles. Les épis mâles, fins et allongés, se dressent en grappes terminales, retombantes lorsqu'ils sont matures. Les épis femelles, enflés, sont portés par un axe spongieux et entourés de nombreuses bractées. Ils sont solitaires, implantés à la base des feuilles. Cette plante est intéressante pour les abeilles car elle occupe de grandes surfaces.')

('OIGNON', 7, 9, 1, 2, 0, 1, 'Cette plante vivace est cultivée sur des surfaces importantes dans le Languedoc mais également un peu partout en France. On la connaît surtout pour ses bulbes solitaires dont les caïeux se gonflent de réserves au goût prononcé, mais la fleur d’oignon est remarquable : elle forme une large sphère de fleurs blanches régulières à six pétales, portée par une hampe creuse. Les feuilles sont cylindriques et creuses également. Sa période de floraison en fait une plante d’appui intéressante, notamment en Méditerranée où les floraisons estivales sont plus rares.')

('PHACELIE', 7, 9, 3, 2, 0, 3, 'Pouvant dépasser 80 cm de hauteur, elle se reconnaît à ses feuilles alternes aux folioles lobées et à ses fleurs bleu lilas regroupées en inflorescences s’enroulant en crosse d'où saillent les cinq étamines. Elle préfère les sols riches, frais et les expositions ensoleillées. Plante originaire de Californie, introduite en 1852, la phacélie peut se rencontrer aux abords des habitations et des décombres. Elle est cultivée, mais sur de faibles surfaces, comme plante fourragère, engrais vert et mellifère : certains la considèrent comme la plante la plus productrice de nectar.')

('TOURNE SOL', 7, 8, 2, 3, 0, 3, 'Les grands capitules du tournesol (50 à 70 cm de diamètre) sont formés d’un disque central de fleurs tubulées entouré d’une couronne extérieure de fleurs jaunes en languettes. Ils prennent une allure penchée caractéristique, tournant le dos à la lumière. Cette plante de grande taille pouvant dépasser 2 m possède une tige simple et des feuilles alternes. Originaire du Mexique et introduit en France, le tournesol est cultivé dans toute la France pour l’huile extraite de ses graines. Comme le colza, il est traité de manière intensive par produits phytosanitaires.');